Connected to base (Python 3.9.7)

In [2]:
import yfinance as yf

dat = yf.Ticker("MSFT")
dat.info

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Microsoft Corporation develops and supports software, services, devices, and solutions worldwide. The Productivity and Business Processes segment offers Microsoft 365 commercial, enterprise mobility + security, windows commercial, power BI, exchange, sharepoint, Microsoft teams, security and compliance, and copilot; Microsoft 365 commercial products, such as Windows commercial on-premises and office licensed services; Microsoft 365 consumer products and cloud services, including Microsoft 365 consumer subscriptions, office licensed on-premises, and other consumer services; LinkedIn; dynamics products and cloud services, such as dynamics 365, cloud-based applications, and on-premises ERP and CRM applications. Its Intelligent Cloud segment provides Server products and cloud services comprising Azure and other cloud services, GitHub, Nuance Healthcare, virtual desktop offerings, and other cloud services; server products, including SQL and windows server, visual studio and system center related client access licenses, and other on-premises offerings; enterprise and partner services, such as enterprise support and nuance professional services, industry solutions, Microsoft partner network, and learning experience. The Personal Computing segment provides windows and devices, such as Windows OEM licensing and devices and surface and PC accessories; gaming services and solutions, such as Xbox hardware, content, and services, first- and third-party content Xbox game pass, subscriptions, and cloud gaming, advertising, and other cloud services; search and news advertising services. It sells its products through OEMs, distributors, and resellers; and online and retail stores. The company has a strategic collaboration with Mayo Clinic, Inc. for the development of a frontier AI model for healthcare; and Global Objects, Inc. to build a retrieval-grounded generative AI world model. The company was founded in 1975 and is headquartered in Redmond, Washington.',
 'fullTimeEmployees': 228000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 58,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 12251294,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 66,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2025,
   'totalPay': 4532750,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 53,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4444191,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Takeshi  Numoto',
   'age': 53,
   'title': 'Executive VP & Chief Marketing Officer',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 2871250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 51,
   'title': 'Executive VP & CEO of Commercial Business',
   'yearBorn': 1974,
   'fiscalYear': 2025,
   'totalPay': 4490115,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Carolina  Dybeck Happe',
   'age': 53,
   'title': 'Executive VP & COO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 59,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1966,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Matthew  Kerner',
   'title': 'CTO & Corporate VP of Worldwide Sales and Solutions',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Jonathan  Neilson',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jonathan M. Palmer',
   'title': 'Corporate Vice President & Chief Legal Officer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 8,
 'compensationRisk': 5,
 'shareHolderRightsRisk': 2,
 'overallRisk': 5,
 'governanceEpochDate': 1780531200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 397.36,
 'open': 395.11,
 'dayLow': 384.07,
 'dayHigh': 396.85,
 'regularMarketPreviousClose': 397.36,
 'regularMarketOpen': 395.11,
 'regularMarketDayLow': 384.0,
 'regularMarketDayHigh': 396.85,
 'dividendRate': 3.64,
 'dividendYield': 0.93,
 'exDividendDate': 1787184000,
 'payoutRatio': 0.20729999,
 'fiveYearAvgDividendYield': 0.79,
 'beta': 1.103,
 'trailingPE': 23.262217,
 'forwardPE': 20.176886,
 'volume': 46218962,
 'regularMarketVolume': 46218962,
 'averageVolume': 35000303,
 'averageVolume10days': 41813280,
 'averageDailyVolume10Day': 41813280,
 'bid': 388.03,
 'ask': 393.97,
 'bidSize': 3,
 'askSize': 4,
 'marketCap': 2899615154176,
 'nonDilutedMarketCap': 2899615202359,
 'fiftyTwoWeekLow': 356.28,
 'fiftyTwoWeekHigh': 555.45,
 'allTimeHigh': 555.45,
 'allTimeLow': 0.088542,
 'priceToSalesTrailing12Months': 9.110466,
 'fiftyDayAverage': 411.3696,
 'twoHundredDayAverage': 454.2874,
 'trailingAnnualDividendRate': 3.56,
 'trailingAnnualDividendYield': 0.00895913,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 2946819162112,
 'profitMargins': 0.39341998,
 'floatShares': 7417514905,
 'sharesOutstanding': 7428434704,
 'sharesShort': 88696120,
 'sharesShortPriorMonth': 79107882,
 'sharesShortPreviousMonthDate': 1777507200,
 'dateShortInterest': 1780012800,
 'sharesPercentSharesOut': 0.0119,
 'heldPercentInsiders': 0.0008,
 'heldPercentInstitutions': 0.7578,
 'shortRatio': 2.42,
 'shortPercentOfFloat': 0.0119,
 'impliedSharesOutstanding': 7428434704,
 'bookValue': 55.777,
 'priceToBook': 6.9982247,
 'lastFiscalYearEnd': 1751241600,
 'nextFiscalYearEnd': 1782777600,
 'mostRecentQuarter': 1774915200,
 'earningsQuarterlyGrowth': 0.231,
 'netIncomeToCommon': 125215997952,
 'trailingEps': 16.78,
 'forwardEps': 19.3459,
 'pegRatio': 1.2,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 9.259,
 'enterpriseToEbitda': 15.976,
 '52WeekChange': -0.1781624,
 'SandP52WeekChange': 0.23713183,
 'lastDividendValue': 0.91,
 'lastDividendDate': 1779321600,
 'quoteType': 'EQUITY',
 'currentPrice': 390.34,
 'targetHighPrice': 870.0,
 'targetLowPrice': 400.0,
 'targetMeanPrice': 561.38763,
 'targetMedianPrice': 555.0,
 'recommendationMean': 1.33929,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 55,
 'totalCash': 78227996672,
 'totalCashPerShare': 10.531,
 'ebitda': 184457003008,
 'totalDebt': 125431996416,
 'quickRatio': 1.142,
 'currentRatio': 1.283,
 'totalRevenue': 318272995328,
 'debtToEquity': 30.271,
 'revenuePerShare': 42.836,
 'returnOnAssets': 0.14814,
 'returnOnEquity': 0.34013999,
 'grossProfits': 217409994752,
 'freeCashflow': 37011251200,
 'operatingCashflow': 170141007872,
 'earningsGrowth': 0.234,
 'revenueGrowth': 0.183,
 'grossMargins': 0.68309,
 'ebitdaMargins': 0.57956004,
 'operatingMargins': 0.46326,
 'financialCurrency': 'USD',
 'symbol': 'MSFT',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'regularMarketChange': -7.01999,
 'regularMarketDayRange': '384.0 - 396.85',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 35000303,
 'fiftyTwoWeekLowChange': 34.059998,
 'fiftyTwoWeekLowChangePercent': 0.09559896,
 'fiftyTwoWeekRange': '356.28 - 555.45',
 'fiftyTwoWeekHighChange': -165.11002,
 'fiftyTwoWeekHighChangePercent': -0.2972545,
 'fiftyTwoWeekChangePercent': -17.81624,
 'dividendDate': 1781136000,
 'earningsTimestamp': 1777492800,
 'earningsTimestampStart': 1785355200,
 'earningsTimestampEnd': 1785355200,
 'earningsCallTimestampStart': 1777498200,
 'earningsCallTimestampEnd': 1777498200,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 16.78,
 'epsForward': 19.3459,
 'epsCurrentYear': 16.81556,
 'priceEpsCurrentYear': 23.213024,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 511108200000,
 'preMarketChange': 2.019989,
 'preMarketChangePercent': 0.51749474,
 'preMarketPrice': 392.36,
 'fiftyDayAverageChange': -21.029602,
 'fiftyDayAverageChangePercent': -0.051120944,
 'twoHundredDayAverageChange': -63.94742,
 'twoHundredDayAverageChangePercent': -0.14076424,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'marketState': 'PRE',
 'regularMarketChangePercent': -1.76666,
 'regularMarketPrice': 390.34,
 'corporateActions': [],
 'preMarketTime': 1781270635,
 'regularMarketTime': 1781208001,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_21835',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'displayName': 'Microsoft',
 'trailingPegRatio': 1.2033}

In [3]:
dat.history(period='1mo')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-05-12 00:00:00-04:00,413.584222,414.602007,405.761170,406.888702,38594200,0.00,0.0
2026-05-13 00:00:00-04:00,402.328624,405.431888,400.163300,404.334259,29667100,0.00,0.0
2026-05-14 00:00:00-04:00,403.605852,410.949931,400.013626,408.545135,27077500,0.00,0.0
2026-05-15 00:00:00-04:00,413.374657,427.244641,412.017611,421.008148,50771200,0.00,0.0
2026-05-18 00:00:00-04:00,415.719606,424.201236,414.711779,422.624664,32564100,0.00,0.0
2026-05-19 00:00:00-04:00,428.970892,431.764859,415.589870,416.517883,33018700,0.00,0.0
2026-05-20 00:00:00-04:00,413.274901,421.187755,410.411078,420.149994,27864000,0.00,0.0
2026-05-21 00:00:00-04:00,424.750000,426.339996,415.709991,419.089996,31393500,0.91,0.0
2026-05-22 00:00:00-04:00,419.540009,424.399994,416.329987,418.570007,22390300,0.00,0.0
2026-05-26 00:00:00-04:00,416.429993,419.769989,413.019989,416.029999,30398000,0.00,0.0
2026-05-27 00:00:00-04:00,411.010010,415.940002,409.579987,412.670013,28901500,0.00,0.0
2026-05-28 00:00:00-04:00,412.980011,429.489990,412.670013,426.989990,47250500,0.00,0.0
2026-05-29 00:00:00-04:00,432.549988,450.329987,432.359985,450.239990,79654400,0.00,0.0
2026-06-01 00:00:00-04:00,464.839996,466.320007,458.269989,460.519989,53628900,0.00,0.0
2026-06-02 00:00:00-04:00,446.880005,453.500000,440.429993,441.309998,37036800,0.00,0.0
2026-06-03 00:00:00-04:00,438.450012,440.390015,424.250000,427.339996,39037000,0.00,0.0
2026-06-04 00:00:00-04:00,435.809998,436.149994,426.410004,428.049988,26899500,0.00,0.0
2026-06-05 00:00:00-04:00,428.339996,429.470001,414.399994,416.670013,34782200,0.00,0.0
2026-06-08 00:00:00-04:00,414.140015,417.160004,408.559998,411.739990,32086700,0.00,0.0
2026-06-09 00:00:00-04:00,409.029999,411.980011,398.480011,403.410004,35317300,0.00,0.0
2026-06-10 00:00:00-04:00,398.549988,405.040009,397.160004,397.359985,32576000,0.00,0.0
2026-06-11 00:00:00-04:00,395.209991,396.850006,384.000000,390.339996,47114000,0.00,0.0

In [4]:
dat.options

('2026-06-12',
 '2026-06-15',
 '2026-06-17',
 '2026-06-18',
 '2026-06-22',
 '2026-06-26',
 '2026-07-02',
 '2026-07-10',
 '2026-07-17',
 '2026-07-24',
 '2026-08-21',
 '2026-09-18',
 '2026-10-16',
 '2026-11-20',
 '2026-12-18',
 '2027-01-15',
 '2027-03-19',
 '2027-06-17',
 '2027-09-17',
 '2027-12-17',
 '2028-01-21',
 '2028-06-16',
 '2028-12-15')

In [6]:
chain = dat.option_chain('2026-06-26') # will have to change the date format, or add code to automatically convert dates into this format
chain

Options(calls=         contractSymbol             lastTradeDate  strike  lastPrice  bid  \
0   MSFT260626C00270000 2026-05-22 17:41:30+00:00   270.0     150.25  0.0
1   MSFT260626C00290000 2026-05-27 16:58:47+00:00   290.0     125.00  0.0
2   MSFT260626C00300000 2026-05-28 13:57:25+00:00   300.0     123.50  0.0
3   MSFT260626C00305000 2026-05-26 15:24:54+00:00   305.0     112.15  0.0
4   MSFT260626C00310000 2026-05-29 14:44:34+00:00   310.0     133.66  0.0
..                  ...                       ...     ...        ...  ...
58  MSFT260626C00535000 2026-06-11 18:35:09+00:00   535.0       0.10  0.0
59  MSFT260626C00540000 2026-06-10 16:20:55+00:00   540.0       0.12  0.0
60  MSFT260626C00545000 2026-06-09 17:43:00+00:00   545.0       0.06  0.0
61  MSFT260626C00550000 2026-06-11 19:03:43+00:00   550.0       0.04  0.0
62  MSFT260626C00555000 2026-06-11 19:22:02+00:00   555.0       0.07  0.0

    ask  change  percentChange  volume  openInterest  impliedVolatility  \
0   0.0     0.0            0.0    10.0             6           0.000010
1   0.0     0.0            0.0     NaN             1           0.000010
2   0.0     0.0            0.0     1.0             2           0.000010
3   0.0     0.0            0.0     NaN             6           0.000010
4   0.0     0.0            0.0    11.0            11           0.000010
..  ...     ...            ...     ...           ...                ...
58  0.0     0.0            0.0     7.0           198           0.250007
59  0.0     0.0            0.0    69.0           192           0.250007
60  0.0     0.0            0.0     3.0            42           0.250007
61  0.0     0.0            0.0     6.0           324           0.250007
62  0.0     0.0            0.0    14.0           510           0.250007

    inTheMoney contractSize currency
0         True      REGULAR      USD
1         True      REGULAR      USD
2         True      REGULAR      USD
3         True      REGULAR      USD
4         True      REGULAR      USD
..         ...          ...      ...
58       False      REGULAR      USD
59       False      REGULAR      USD
60       False      REGULAR      USD
61       False      REGULAR      USD
62       False      REGULAR      USD

[63 rows x 14 columns], puts=         contractSymbol             lastTradeDate  strike  lastPrice  bid  \
0   MSFT260626P00270000 2026-06-09 19:53:27+00:00   270.0       0.04  0.0
1   MSFT260626P00280000 2026-06-11 17:25:39+00:00   280.0       0.07  0.0
2   MSFT260626P00290000 2026-06-11 14:59:35+00:00   290.0       0.11  0.0
3   MSFT260626P00300000 2026-06-11 16:50:02+00:00   300.0       0.11  0.0
4   MSFT260626P00305000 2026-06-04 17:28:09+00:00   305.0       0.11  0.0
5   MSFT260626P00310000 2026-06-11 15:01:55+00:00   310.0       0.12  0.0
6   MSFT260626P00315000 2026-06-01 16:17:31+00:00   315.0       0.10  0.0
7   MSFT260626P00320000 2026-06-11 18:24:07+00:00   320.0       0.21  0.0
8   MSFT260626P00325000 2026-06-11 18:56:59+00:00   325.0       0.30  0.0
9   MSFT260626P00330000 2026-06-11 18:24:29+00:00   330.0       0.36  0.0
10  MSFT260626P00335000 2026-06-11 19:43:21+00:00   335.0       0.42  0.0
11  MSFT260626P00340000 2026-06-11 19:34:51+00:00   340.0       0.59  0.0
12  MSFT260626P00345000 2026-06-11 19:59:41+00:00   345.0       0.50  0.0
13  MSFT260626P00350000 2026-06-11 19:53:49+00:00   350.0       0.90  0.0
14  MSFT260626P00355000 2026-06-11 19:59:41+00:00   355.0       1.04  0.0
15  MSFT260626P00360000 2026-06-11 19:52:57+00:00   360.0       1.70  0.0
16  MSFT260626P00365000 2026-06-11 19:58:36+00:00   365.0       2.30  0.0
17  MSFT260626P00370000 2026-06-11 19:55:12+00:00   370.0       3.09  0.0
18  MSFT260626P00375000 2026-06-11 19:57:51+00:00   375.0       4.26  0.0
19  MSFT260626P00380000 2026-06-11 19:57:45+00:00   380.0       6.20  0.0
20  MSFT260626P00385000 2026-06-11 19:55:04+00:00   385.0       7.67  0.0
21  MSFT260626P00390000 2026-06-11 19:57:14+00:00   390.0       9.90  0.0
22  MSFT260626P00395000 2026-06-11 19:54:08+00:00   395.0      12.57  0.0
23  MSFT260626P00397500 2026-06-11 19:40:18+00:00   397.5      15.65  0.0
24  MSFT260626P00400000 2026-06-11 19:57:20+00:00   400.0      15.32  0.0
25  MSFT260626P00402500 2026-06-11 19:11:43+00:00   402.5      19.00  0.0
26  MSFT260626P00405000 2026-06-11 19:37:38+00:00   405.0      20.75  0.0
27  MSFT260626P00407500 2026-06-11 19:41:50+00:00   407.5      22.36  0.0
28  MSFT260626P00410000 2026-06-11 19:49:33+00:00   410.0      23.30  0.0
29  MSFT260626P00412500 2026-06-11 19:45:49+00:00   412.5      26.03  0.0
30  MSFT260626P00415000 2026-06-11 19:59:49+00:00   415.0      26.86  0.0
31  MSFT260626P00417500 2026-06-11 14:33:46+00:00   417.5      30.04  0.0
32  MSFT260626P00420000 2026-06-11 19:48:02+00:00   420.0      32.59  0.0
33  MSFT260626P00422500 2026-06-11 14:46:18+00:00   422.5      33.09  0.0
34  MSFT260626P00425000 2026-06-11 19:35:56+00:00   425.0      37.94  0.0
35  MSFT260626P00427500 2026-06-11 15:58:54+00:00   427.5      41.55  0.0
36  MSFT260626P00430000 2026-06-11 18:07:49+00:00   430.0      42.41  0.0
37  MSFT260626P00432500 2026-06-11 17:30:31+00:00   432.5      44.60  0.0
38  MSFT260626P00435000 2026-06-11 17:49:01+00:00   435.0      47.50  0.0
39  MSFT260626P00437500 2026-06-11 19:35:56+00:00   437.5      49.09  0.0
40  MSFT260626P00440000 2026-06-11 19:56:29+00:00   440.0      50.16  0.0
41  MSFT260626P00445000 2026-06-11 15:59:38+00:00   445.0      58.60  0.0
42  MSFT260626P00450000 2026-06-11 19:14:09+00:00   450.0      62.72  0.0
43  MSFT260626P00455000 2026-06-11 17:01:54+00:00   455.0      68.35  0.0
44  MSFT260626P00460000 2026-06-11 18:02:33+00:00   460.0      71.63  0.0
45  MSFT260626P00465000 2026-06-09 14:56:05+00:00   465.0      58.50  0.0
46  MSFT260626P00470000 2026-06-09 14:09:08+00:00   470.0      58.96  0.0
47  MSFT260626P00475000 2026-06-08 18:31:35+00:00   475.0      62.73  0.0
48  MSFT260626P00480000 2026-06-11 14:58:08+00:00   480.0      92.67  0.0
49  MSFT260626P00485000 2026-06-01 15:15:32+00:00   485.0      30.56  0.0
50  MSFT260626P00490000 2026-06-09 18:12:36+00:00   490.0      86.96  0.0
51  MSFT260626P00495000 2026-06-01 15:33:18+00:00   495.0      38.09  0.0
52  MSFT260626P00500000 2026-06-03 13:32:30+00:00   500.0      61.10  0.0
53  MSFT260626P00505000 2026-06-08 13:32:47+00:00   505.0      91.80  0.0
54  MSFT260626P00510000 2026-06-04 19:59:55+00:00   510.0      81.85  0.0
55  MSFT260626P00515000 2026-06-08 13:37:01+00:00   515.0     101.75  0.0
56  MSFT260626P00520000 2026-06-01 14:48:41+00:00   520.0      59.48  0.0
57  MSFT260626P00525000 2026-06-01 14:48:41+00:00   525.0      64.13  0.0
58  MSFT260626P00540000 2026-06-10 16:08:58+00:00   540.0     137.59  0.0
59  MSFT260626P00550000 2026-06-01 13:30:28+00:00   550.0      84.85  0.0

    ask  change  percentChange  volume  openInterest  impliedVolatility  \
0   0.0     0.0            0.0     4.0           179           0.250007
1   0.0     0.0            0.0     1.0            94           0.250007
2   0.0     0.0            0.0     1.0            13           0.250007
3   0.0     0.0            0.0    22.0            31           0.250007
4   0.0     0.0            0.0     1.0             7           0.250007
5   0.0     0.0            0.0     1.0            19           0.250007
6   0.0     0.0            0.0     4.0            32           0.250007
7   0.0     0.0            0.0     7.0            38           0.250007
8   0.0     0.0            0.0    12.0           113           0.250007
9   0.0     0.0            0.0    12.0           334           0.125009
10  0.0     0.0            0.0    32.0            65           0.125009
11  0.0     0.0            0.0    38.0           123           0.125009
12  0.0     0.0            0.0   321.0           497           0.125009
13  0.0     0.0            0.0   592.0          1055           0.125009
14  0.0     0.0            0.0    85.0           251           0.125009
15  0.0     0.0            0.0   866.0           977           0.062509
16  0.0     0.0            0.0   691.0          1012           0.062509
17  0.0     0.0            0.0   362.0           602           0.062509
18  0.0     0.0            0.0   434.0           904           0.031260
19  0.0     0.0            0.0  1479.0          1014           0.031260
20  0.0     0.0            0.0  1210.0          1047           0.015635
21  0.0     0.0            0.0   630.0          1180           0.001963
22  0.0     0.0            0.0   445.0          1039           0.000010
23  0.0     0.0            0.0    80.0           174           0.000010
24  0.0     0.0            0.0   483.0          2607           0.000010
25  0.0     0.0            0.0    20.0           220           0.000010
26  0.0     0.0            0.0    82.0          1273           0.000010
27  0.0     0.0            0.0    15.0           229           0.000010
28  0.0     0.0            0.0    86.0          1413           0.000010
29  0.0     0.0            0.0    17.0           188           0.000010
30  0.0     0.0            0.0    69.0           768           0.000010
31  0.0     0.0            0.0     1.0           145           0.000010
32  0.0     0.0            0.0   109.0           959           0.000010
33  0.0     0.0            0.0     2.0            26           0.000010
34  0.0     0.0            0.0    75.0           994           0.000010
35  0.0     0.0            0.0     2.0             9           0.000010
36  0.0     0.0            0.0    45.0          1528           0.000010
37  0.0     0.0            0.0     7.0            33           0.000010
38  0.0     0.0            0.0    18.0           369           0.000010
39  0.0     0.0            0.0     3.0            21           0.000010
40  0.0     0.0            0.0    20.0           187           0.000010
41  0.0     0.0            0.0    12.0           896           0.000010
42  0.0     0.0            0.0    21.0           218           0.000010
43  0.0     0.0            0.0     2.0             7           0.000010
44  0.0     0.0            0.0    10.0            25           0.000010
45  0.0     0.0            0.0     1.0             0           0.000010
46  0.0     0.0            0.0     8.0             0           0.000010
47  0.0     0.0            0.0     1.0             1           0.000010
48  0.0     0.0            0.0     1.0             1           0.000010
49  0.0     0.0            0.0    27.0             1           0.000010
50  0.0     0.0            0.0     5.0             0           0.000010
51  0.0     0.0            0.0    18.0             0           0.000010
52  0.0     0.0            0.0     2.0             0           0.000010
53  0.0     0.0            0.0     1.0             0           0.000010
54  0.0     0.0            0.0     NaN             0           0.000010
55  0.0     0.0            0.0     1.0             0           0.000010
56  0.0     0.0            0.0     2.0             0           0.000010
57  0.0     0.0            0.0     NaN             0           0.000010
58  0.0     0.0            0.0     1.0             0           0.000010
59  0.0     0.0            0.0     1.0             0           0.000010

    inTheMoney contractSize currency
0        False      REGULAR      USD
1        False      REGULAR      USD
2        False      REGULAR      USD
3        False      REGULAR      USD
4        False      REGULAR      USD
5        False      REGULAR      USD
6        False      REGULAR      USD
7        False      REGULAR      USD
8        False      REGULAR      USD
9        False      REGULAR      USD
10       False      REGULAR      USD
11       False      REGULAR      USD
12       False      REGULAR      USD
13       False      REGULAR      USD
14       False      REGULAR      USD
15       False      REGULAR      USD
16       False      REGULAR      USD
17       False      REGULAR      USD
18       False      REGULAR      USD
19       False      REGULAR      USD
20       False      REGULAR      USD
21       False      REGULAR      USD
22        True      REGULAR      USD
23        True      REGULAR      USD
24        True      REGULAR      USD
25        True      REGULAR      USD
26        True      REGULAR      USD
27        True      REGULAR      USD
28        True      REGULAR      USD
29        True      REGULAR      USD
30        True      REGULAR      USD
31        True      REGULAR      USD
32        True      REGULAR      USD
33        True      REGULAR      USD
34        True      REGULAR      USD
35        True      REGULAR      USD
36        True      REGULAR      USD
37        True      REGULAR      USD
38        True      REGULAR      USD
39        True      REGULAR      USD
40        True      REGULAR      USD
41        True      REGULAR      USD
42        True      REGULAR      USD
43        True      REGULAR      USD
44        True      REGULAR      USD
45        True      REGULAR      USD
46        True      REGULAR      USD
47        True      REGULAR      USD
48        True      REGULAR      USD
49        True      REGULAR      USD
50        True      REGULAR      USD
51        True      REGULAR      USD
52        True      REGULAR      USD
53        True      REGULAR      USD
54        True      REGULAR      USD
55        True      REGULAR      USD
56        True      REGULAR      USD
57        True      REGULAR      USD
58        True      REGULAR      USD
59        True      REGULAR      USD  , underlying={'language': 'en-US', 'region': 'US', 'quoteType': 'EQUITY', 'typeDisp': 'Equity', 'quoteSourceName': 'Delayed Quote', 'triggerable': True, 'customPriceAlertConfidence': 'HIGH', 'currency': 'USD', 'regularMarketChangePercent': -1.76666, 'regularMarketPrice': 390.34, 'marketState': 'PRE', 'earningsTimestamp': 1777492800, 'earningsTimestampStart': 1785355200, 'earningsTimestampEnd': 1785355200, 'earningsCallTimestampStart': 1777498200, 'earningsCallTimestampEnd': 1777498200, 'isEarningsDateEstimate': True, 'trailingAnnualDividendRate': 3.56, 'trailingPE': 23.262217, 'dividendRate': 3.64, 'trailingAnnualDividendYield': 0.00895913, 'dividendYield': 0.93, 'epsTrailingTwelveMonths': 16.78, 'epsForward': 19.3459, 'epsCurrentYear': 16.81556, 'priceEpsCurrentYear': 23.213024, 'sharesOutstanding': 7428434704, 'impliedSharesOutstanding': 7428434704, 'bookValue': 55.777, 'fiftyDayAverage': 411.3696, 'fiftyDayAverageChange': -21.029602, 'fiftyDayAverageChangePercent': -0.051120944, 'twoHundredDayAverage': 454.2874, 'twoHundredDayAverageChange': -63.94742, 'twoHundredDayAverageChangePercent': -0.14076424, 'marketCap': 2899615154176, 'forwardPE': 20.176886, 'priceToBook': 6.9982247, 'sourceInterval': 15, 'exchangeDataDelayedBy': 0, 'averageAnalystRating': '1.3 - Strong Buy', 'tradeable': False, 'cryptoTradeable': False, 'corporateActions': [], 'preMarketTime': 1781270647, 'regularMarketTime': 1781208001, 'exchange': 'NMS', 'messageBoardId': 'finmb_21835', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EDT', 'gmtOffSetMilliseconds': -14400000, 'market': 'us_market', 'esgPopulated': False, 'shortName': 'Microsoft Corporation', 'longName': 'Microsoft Corporation', 'hasPrePostMarketData': True, 'firstTradeDateMilliseconds': 511108200000, 'priceHint': 2, 'preMarketChange': 2.1600037, 'preMarketChangePercent': 0.5533647, 'preMarketPrice': 392.5, 'regularMarketChange': -7.01999, 'regularMarketDayHigh': 396.85, 'regularMarketDayRange': '384.0 - 396.85', 'regularMarketDayLow': 384.0, 'regularMarketVolume': 46218962, 'regularMarketPreviousClose': 397.36, 'bid': 388.03, 'ask': 393.97, 'bidSize': 3, 'askSize': 4, 'fullExchangeName': 'NasdaqGS', 'financialCurrency': 'USD', 'regularMarketOpen': 395.11, 'averageDailyVolume3Month': 35000303, 'averageDailyVolume10Day': 41813280, 'fiftyTwoWeekLowChange': 34.059998, 'fiftyTwoWeekLowChangePercent': 0.09559896, 'fiftyTwoWeekRange': '356.28 - 555.45', 'fiftyTwoWeekHighChange': -165.11002, 'fiftyTwoWeekHighChangePercent': -0.2972545, 'fiftyTwoWeekLow': 356.28, 'fiftyTwoWeekHigh': 555.45, 'fiftyTwoWeekChangePercent': -17.81624, 'dividendDate': 1781136000, 'displayName': 'Microsoft', 'symbol': 'MSFT'})

In [9]:
calls = chain.calls
calls.head()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,MSFT260626C00270000,2026-05-22 17:41:30+00:00,270.0,150.25,0.0,0.0,0.0,0.0,10.0,6,0.00001,True,REGULAR,USD
1,MSFT260626C00290000,2026-05-27 16:58:47+00:00,290.0,125.00,0.0,0.0,0.0,0.0,NaN,1,0.00001,True,REGULAR,USD
2,MSFT260626C00300000,2026-05-28 13:57:25+00:00,300.0,123.50,0.0,0.0,0.0,0.0,1.0,2,0.00001,True,REGULAR,USD
3,MSFT260626C00305000,2026-05-26 15:24:54+00:00,305.0,112.15,0.0,0.0,0.0,0.0,NaN,6,0.00001,True,REGULAR,USD
4,MSFT260626C00310000,2026-05-29 14:44:34+00:00,310.0,133.66,0.0,0.0,0.0,0.0,11.0,11,0.00001,True,REGULAR,USD

In [23]:
# try with applicable data, RVMD260918C160-- 2026-09-18, 160 call
import pandas as pd

rvmd = yf.Ticker('RVMD')
chain = rvmd.option_chain('2026-09-18')
calls = chain.calls
# calls[calls['contractSymbol'] == 'RVMD260918C160'] # this doesn't work, the symbnol in the spreadsheet is different(?)

calls[calls['strike']==160]

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
21,RVMD260918C00160000,2026-06-10 17:57:13+00:00,160.0,12.1,0.0,0.0,0.0,0.0,2.0,288,0.03126,False,REGULAR,USD